# Run CI on all Zeek packages
name: Zeek Package CI

on:
  push:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  get_zkgs:
    name: Get package list
    runs-on: ubuntu-20.04
    outputs:
      packages: ${{ steps.zkg_list.outputs.packages }}

    steps:
      - id: install
        run: pip install zkg
      - id: zkg_list
#        run: echo "::set-output name=packages::{\"packages\":[$($HOME/.local/bin/zkg list all | head -n 5 | awk '{print "\"" $1 "\""}' | paste -d, -s -)]}"
        run: | 
          echo "packages={\"packages\":[$($HOME/.local/bin/zkg list all | head -n 5 | awk '{print "\"" $1 "\""}' | paste -d, -s -)]}" >> $GITHUB_OUTPUT
#          echo $GITHUB_OUTPUT

  run_ci:
    name: Test ${{ matrix.packages }}
    needs: get_zkgs
    continue-on-error: true
    runs-on: ubuntu-20.04
#    container:
#      image: grigorescu/zeek_centos_8:latest
    strategy:
      matrix: ${{fromJson(needs.get_zkgs.outputs.packages)}}
      fail-fast: false
#    outputs: {"package":"${{ steps.zkg_test.outputs.DOP_TEST }}"}
    outputs:
      package: "${{ steps.zkg_test.outputs.DOP_TEST }}"
      all_stuff: $GITHUB_OUTPUT
#    outputs: {"${{ matrix.packages }}":"${{ steps.zkg_test.outputs }}"}
    steps:
    - uses: actions/checkout@v1

    - id: zkg_test
      run: |
        export PATH=/usr/local/zeek/bin:$HOME/.local/bin:$PATH
        echo zkg test ${{ matrix.packages }} || $GITHUB_WORKSPACE/debug.sh ${{ matrix.packages }}
        echo "${{ matrix.packages }}=[{\"${{ matrix.packages }}\": {\"status\": \"passed\"}}]" >> $GITHUB_OUTPUT
        echo "DOP_TEST=DOP_VALUE_${{ matrix.packages}}" >> $GITHUB_OUTPUT

  summary:
    name: Summarize Results
    needs: run_ci
    # We force this to run, even if run_ci jobs have failed
    if: true
    runs-on: ubuntu-20.04
    env:
      NEEDS_CONTEXT: ${{ toJson(needs) }}
    steps:
      - run: echo "$NEEDS_CONTEXT"
      - run: echo "DOP ${{ needs.run_ci.outputs.all_stuff }}"
      - run: echo "DOP2 ${{ needs.run_ci.outputs.package }}"
      - run: env
